version: "2.1"
services:
  api:
    build: .
    ports:
    - "8081:8081"
    depends_on:
    - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/recipes_ms
      PORT: 8081
    healthcheck:
      test: curl http://192.168.92.100:8081
      interval: 5s
      timeout: 3s
      retries: 5
  mongo:
    image: mongo
    ports:
    - "27017:27017"
