module.exports = [
  {
    user_id: 1,
    name: "LASAGNA DE CARNE MOLIDA",
    description: "La lasagna es un platillo típico de Italia, con esta receta sentirás que estás en uno de los mejores restaurantes de Italia. Queda deliciosa te lo prometo!",
    difficulty_id: 2,
    preparation_time: 50,
    portions: 8,
    user_id: 1,
    ingredients: ["2 cucharadas de aceite de oliva",
    "1/2 cebolla picada",
    "2 dientes de ajo picadito",
    "1 zanahoria picadita",
    "1 rodaja de jitomate saladet partidos a la mitad",
    "1 lata de puré de tomate grande",
    "1 cebolla picada finamente",
    "1 diente de ajo picaditos",
    "1 kilo de carne molida",
    "1 vaso de vino blanco seco",
    "3/4 de kilo de queso ricotta",
    "2 huevos",
    "1/2 rodaja de queso mozzarella rallado",
    "2 tazas de queso parmesano rallado",
    "1/2 taza de perejil picadito",
    "lasagnas",
    "sal",
    "pimientas",
    "nueces moscada"],
    steps:[
      "Saltear la cebolla, el ajo y zanahoria, agregar el jitomate y puré y dejar en lumbre muy bajita una vez que hierva como una hora, pasar por el colador y reservar la salsa boloñesa.",
      "Acitronar la cebolla y ajo a que se coloree como 20 min en el aceite olivo, agregar las carnes y dejar a que no estén rositas, agregar el jitomate preparado, el vino; condimentar con sal y pimienta.",
      "Revolver el queso ricotta con los huevos, 1 taza del parmesano, perejil, sal, pimienta y nuez moscada.",
      "Poner a hervir en agua con sal las hojas de lasaña y dejar al dente. Escurrir y reservar.",
      "Engrasar un molde refractario con mantequilla. Poner una capa de pasta, luego el queso ricotta y extender con una espátula poner salsa de carne y queso mozzarella, así sucesivamente a terminar con pasta, ricotta y queso.",
      "Tapar con papel aluminio y hornear 20 minutos. Quitar el papel aluminio y dejar a que esté ligeramente dorada como 10 min más."
    ]
  },
  {
    user_id: 2,
    name: "ARROZ CHINO",
    description: "La mejor receta de arroz chino que podrás encontrar, prepárala y sorprende a todos tus invitados con esta fabulosa receta de arroz chino con verduritas.",
    difficulty_id: 2,
    preparation_time: 50,
    portions:6,
    ingredients:[
      "6 tazas de Arroz SOS® Calrose (Sushi)",
      "250 gramos de pechuga de pollo o jamon",
      "salsas de soya al gusto",
      "aceites",
      "1 cebolla picada",
      "10 ramitas de cebollín picado",
      "3 zanahorias picadas",
      "2 calabazas picadas",
      "2 tazas de germen de soya",
      "3 huevos",
      "1 cucharadita de sal",
      "2 cucharadas de caldo de pollo"
    ],
    steps:[
      "Rebanar el pollo muy fino y mezclar con la salsa de soya.",
      "Batir los huevos y cocinarlos en un sartén caliente con un poco de aceite, picarlo y reservar.",
      "Freír cebolla en 3 cucharadas de aceite por 10 minutos, agregar el pollo y freír 2 minutos. Sacar del fuego y reservar caliente.",
      "En el mismo sartén agregar aceite y freír las demás verduras y cuando estén listas sacar del fuego.",
      "Calentar un sartén grande poner 2 cucharadas de aceite, agregar el arroz y mover un minuto. Agregar la sal y el caldo. Mover 2 minutos más.",
      "Poner la cebolla, pollo, huevo y verduras y mezclar con cuidado. Servir caliente."
    ],
  },
  {
    user_id: 3,
    name: "PIZZA DE CHOCOLATE CON BOMBÓN",
    description: "Esta pizza de chocolate con bombón es ideal para sorprender a tu novio en un día de san valentín o cualquier cena que le quieras preparar de sorpresa.",
    difficulty_id: 1,
    preparation_time: 40,
    portions: 6,
    ingredients:[
      "150 gramos de crema de avellanas",
      "500 gramos de harina",
      "30 gramos de azúcar",
      "40 mililitros de aceite",
      "10 gramos de sal",
      "1 sobre de levadura",
      "50 gramos de mantequilla",
      "250 mililitros de agua",
      "2 tazas de bombón chico blanco"
    ],
    steps:[
      "Mezclar todos los ingredientes secos.",
      "Agregar la mantequilla, el aceite y por último el agua.",
      "Fermentar la masa por 20 minutos aproximadamente.",
      "Extender la masa con la ayuda de un rodillo, picar la masa con un tenedor para que no se infle.",
      "Hornear la masa por 25 minutos a 180ºC.",
      "Untar la crema de avellanas, espolvorear los bombones.",
      "Meter la pizza al horno por 2 minutos y listo."
    ],
  },
  {
    user_id: 1,
    name: "PASTEL DE CREPAS CON FRESAS",
    description: "Si preparas este original pastel de crepas con fresas con crema, lo vas a querer compartir con quien más quieres. Además de fácil de hacer, es muy rico porque lleva capas de crema batida aromatizada con ralladura de limón y fresas.",
    difficulty_id: 3,
    preparation_time: 95,
    portions: 6,
    ingredients:[
      "2 tazas de leche",
      "1 taza de harina",
      "1/4 de taza de mantequilla fundida",
      "2 piezas de huevo",
      "1/8 de taza de azúcar",
      "1 cucharadita de vainilla",
      "1 cucharadita de canela en polvo",
      "3 tazas de crema para batir",
      "3 cucharadas de ralladura de limón amarillo",
      "1 cucharada de jugo de limón",
      "1/2 taza de azúcar glass",
      "3 tazas de fresa cortadas en láminas"
    ],
    steps:[
      "En un bowl mezcla todos los ingredientes de las crepas hasta formar un mezcla homogénea.",
      "Calienta una sartén a fuego medio y forma crepas hasta conseguir el número de crepas deseadas para las capas del pastel. Reserva.",
      "En un bowl bate la crema para batir hasta que doble su volumen, agrega la ralladura de limón, el jugo de limón y el azúcar glass. Reserva.",
      "En un plato coloca una crepa de base, unta una capa de crema batida y agrega fresas. Repite hasta formar varias capas.",
      "Cubre todo el pastel con crema batida, decora la parte de arriba con abundantes fresas. Refrigera 1 hora, sirve y disfruta."
    ],
  },
  {
    user_id: 2,
    name: "ENSALADA DE PASTA HAWAIANA",
    description: "Prepara esta rica receta de pasta de tornillos mezclada con piña, jamón, cebolla morada, un poco de apio fresco y zanahoria, con un toque cremosito de mayonesa, crema y mostaza. Esta ensalada de pasta hawaiana le va a encantar a toda tu familia. Lo mejor de todo es que se prepara en 25 minutos.",
    difficulty_id: 1,
    preparation_time: 22,
    portions: 6,
    ingredients:[
      "2 litros de agua",
      "1 cucharada de sal",
      "1 taza de pasta corta",
      "2 tazas de piña en almíbar cortada en cubos pequeños",
      "2 tazas de jamón de pavo cortado en cubos pequeños",
      "1/4 de taza de cebolla morada finamente picada",
      "1 taza de apio cortado en cubos pequeños",
      "1 taza de zanahoria cortada en tiras finas",
      "1 cucharada de mostaza",
      "1/2 taza de crema ácida",
      "2 cucharadas de mayonesa",
      "al gusto de sal y pimienta",
      "al gusto de cilantro para decorar"
    ],
    steps:[
      "Para la pasta, en una olla calienta el agua hasta que llegue a punto de ebullición, agrega la sal y añade la pasa para que se cocine al dente, de acuerdo a las instrucciones del empaque. Retira de cocción, cuela, enfría y reserva.",
      "En un bowl mezcla la pasta con la piña, el jamón, la cebolla, el apio, la zanahoria, agrega la mostaza, la crema, la mayonesa, sazona con sal y pimienta a tu gusto. Mezcla en forma envolvente hasta que todos los ingredientes estén cremositos. Sirve con hojitas de cilantro y disfruta."
    ],
  },
  {
    user_id: 3,
    name: "BISQUE DE LANGOSTA",
    description: "La sopa de langosta es una crema elegante hecha de los jugos y las fragancias de la langosta. Esta sopa es ideal para una noche de langosta ya que la sopa solo usa la cáscara de langosta pero no su carne.",
    difficulty_id: 2,
    preparation_time: 120,
    portions: 4,
    ingredients:[
      "4 piezas de cuerpo de langosta sin carne",
      "2 cucharadas de mantequilla",
      "1 trozo de cebolla finamente picada",
      "1 trozo de zanahoria picada",
      "1 rama de apio",
      "1 diente de ajo",
      "3 cucharadas de puré de tomate",
      "2 cucharadas de brandy",
      "6 tazas de agua",
      "2 tazas de caldo de langosta",
      "3 cucharadas de harina",
      "pimienta al gusto",
      "1 pizca de nuez moscada",
      "1 taza de crema"
    ],
    steps:[
      "En una cacerola grande, derrita la mantequilla a fuego medio. Dorar la cebolla, las zanahorias, el ajo y cocinar durante 5 minutos.",
      "Agregue el puré de tomate y los cuerpos de langosta y continúe cocinando durante 5 minutos.",
      "Agregue el brandy y cocine por 5 minutos más.",
      "Agregue el agua, el caldo de langosta y las especias y cocine hasta que hierva.",
      "Reduzca a fuego medio y cocine la sopa durante 60 minutos, permitiendo que el caldo se espese.",
      "Pasar la sopa a través de un tamiz muy fino y volver a la olla. Continúa cocinando y con un mezclador de globos, agrega la crema poco a poco. Servir",
    ],
  },
  {
    user_id: 1,
    name: "JUGO DE PEPINO, LIMÓN Y ALBAHACA",
    description: "En estos días de calor comienza tus mañanas con un refrescante jugo de pepino con limón y albahaca que se prepara en un dos por tres y es muy nutritivo, y tiene un sabor único y muy diferente a los jugos convencionales.",
    difficulty_id: 1,
    preparation_time: 3,
    portions: 4,
    ingredients:[
      "6 pepinos",
      "3 limones sin semilla, en mitades",
      "4 ramitas de albahaca"
    ],
    steps:[
      "Coloca los pepinos en la juguera y procesa.",
      "Agrega los limones y dos ramitas de albahaca y procesa.",
      "Sirve en un vaso con hielos y decora con más albahaca fresca."
    ],
  },
  {
    user_id: 2,
    name: "TAMALES DE NUEZ",
    description: "Disfruta de estos deliciosos tamales de nuez calientitos, ideales para acompañarlos con un cafecito o un atole. Tienen una esponjosita y suave consistencia gracias a la combinación de harina de maíz con harina de arroz. En este caso la nuez es el ingrediente principal que perfuma la masa con gran intensidad. Para servir estos tamales se les da el toque final con un poco de chocolate fundido, que los hace irresistibles. Son una preparación muy sencilla, perfecta para desayunar, comer o cenar. ¡Con su delicioso sabor a nuez, estos tamalitos te sacarán de cualquier apuro!",
    difficulty_id: 1,
    preparation_time: 90,
    portions: 12,
    ingredients:[
      "12 piezas de hoja de maíz",
      "4 tazas de agua caliente",
      "1 1/2 tazas de mantequilla",
      "1 1/2 tazas de azúcar",
      "2 tazas de harina de maíz",
      "1 1/2 tazas de harinas de arroz",
      "1 cucharadita de polvo para hornear",
      "1 taza de leche",
      "1 cucharada de esencia de nuez",
      "1 1/2 tazas de nuez finamente picadas",
      "al gusto de nuez picada para decorar",
      "al gusto de chocolate derretido, para decorar"
    ],
    steps:[
      "Remoja las hojas de maíz con agua hasta que se suavicen. Reserva.",
      "Bate la mantequilla con el azúcar, hasta que esté cremosa.",
      "Agrega la harina de maíz, la harina de arroz, polvo para hornear, la leche, la esencia y las nueces bate hasta integrar.",
      "Coloca tres cucharadas de masa sobre una hoja de tamal, cierra y dobla.",
      "Coloca sobre una vaporera los tamales y cocina por 1 hora."
    ],
  },
  {
    user_id: 3,
    name: "SUSHI DE SURIMI",
    description: "Delicioso sushi de surimi, queda delicioso y súper fácil de hacer, es ideal para comer en cualquier ocasión. Le encantará a todos.",
    difficulty_id: 1,
    preparation_time: 30,
    portions: 4,
    ingredients:[
      "300 gramos de arroz de sushi",
      "2 cucharadas de vinagre de arroz o de vino blanco",
      "1 aguacate grande",
      "1/2 jugo de limón",
      "4 hojas de alga nori",
      "200 gramos de surimi cortado en tiras",
      "salsas de soya para servir",
      "1/2 pepino cortado en tiras",
      "1 zanahoria cortado en tiras",
      "150 gramos de Queso Philadephia cortado en tiras"
    ],
    steps:[
      "Poner el arroz en una cacerola pequeña con 600ml de agua. Llevar a ebullición y cocer por 10 minutos o hasta que el agua se absorba y el arroz esté tierno. Revuelva con el vinagre cubrir y dejar enfriar.",
      "Divida el arroz entre las hojas de nori y extender uniformemente, dejando un borde de 1 cm en la parte superior e inferior. Coloque sobre el arroz, el surimi, la zanahoria, el pepino y el queso crema.",
      "Doble el borde inferior de las hojas de algas nori sobre el relleno y enrolle firmemente.",
      "Humedezca el borde superior con un poco de agua para ayudar a sellar el rollo. Repita el procedimiento para hacer 4 rollos. En esta etapa, los rollos pueden ser envueltos ​​individualmente en film de plástico adherente y se dejan enfriar hasta que estén listos para servir.",
      "Con un cuchillo de sierra (mojado), cortar cada rollo en 8 rodajas.",
      "Servir acompañado de salsa de soya."
    ],
  },
  {
    user_id: 1,
    name: "BROWNIES",
    description: "Un delicioso postre de chocolate, son los clásicos brownies. Sigue la receta y verás cuán ricos son, ¡en tu casa terminarán en un día!",
    difficulty_id: 3,
    preparation_time: 45,
    portions: 4,
    ingredients:[
      "1 taza de harina",
      "2 tazas de azucar",
      "2 barritas de mantequilla 90 gc / u",
      "1/2 taza de cacao",
      "4 huevos",
      "1/2 cucharada de polvo de hornear",
      "1 cucharada de vainilla"
    ],
    steps:[
      "Derretir los palitos de mantequilla y batir con el azúcar.",
      "Agregue los huevos, la harina, el cacao y el polvo de hornear uno por uno mientras revuelve.",
      "Cuando todos los ingredientes estén incorporados, agregue las nueces y la vainilla.",
      "Engrasar un molde rectangular o cuadrado con mantequilla y vaciar la mezcla.",
      "Poner en horno precalentado a 175 ° C durante 40 minutos."
    ],
  },
  {
    user_id: 2,
    name: "SOPA TARASCA",
    description: "Prepara esta Deliciosa Sopa Tarasca originaria de Pátzcuaro Michoacán. Está hecha a base de frijol con jitomate y tortilla de maíz. Ésta sopa es una receta nutritiva que puedes servir como entrada o cómo único plato ya que tiene muchos ingredientes que crean una comida completa sin carne. ",
    difficulty_id: 1,
    preparation_time: 35,
    portions: 2,
    ingredients:[
      "1/2 pieza de cebolla cortada en octavos",
      "1 diente de ajo cortado en trozos",
      "2 piezas de jitomate cortados en cubos",
      "1 taza de frijol cocido",
      "1 taza de caldo de pollo",
      "2 piezas de chile pasilla limpio, remojado y sin semillas",
      "2 tazas de caldo de pollo",
      "2 hojas de laurel seco",
      "1 cucharadita de tomillo",
      "1 cucharadita de mejorana",
      "suficiente de aceite",
      "1 taza de tortillas de maíz cortada en tiritas",
      "1/2 taza de chile ancho cortado en finas tiras",
      "suficiente de crema ácida para servir",
      "suficiente de queso fresco desmoronado, para servir",
      "suficiente de aguacate para servir"
    ],
    steps:[
      "Calienta un comal a fuego alto y asa la cebolla, el ajo, el jitomate. Retira.",
      "Licúa los ingredientes que asaste con anterioridad con los frijoles, el caldo de frijol, el chile pasilla, el caldo de pollo, el laurel, el tomillo y la mejorana hasta obtener una mezcla homogénea.",
      "Calienta una sartén con un poco de aceite y cocina la preparación anterior hasta que esté cocida.",
      "Calienta un sartén a fuego medio con el aceite, fríe las julianas de tortilla hasta que estén crujientes, retira del aceite y coloca en papel absorbente. Fríe las tiras de chile ancho sin que se quemen, repite el mismo proceso y reserva.",
      "En un plato hondo sirve la sopa, acompaña con la crema ácida, las tiras de tortilla frita, el chile ancho frito, el queso fresco y aguacate. Disfruta."
    ]
  }
]
